name: Create Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # or yarn install

    - name: Extract version from manifest.json
      id: manifest
      run: echo "::set-output name=version::$(node -p "require('./manifest.json').version")"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.manifest.outputs.version }}
        release_name: Release ${{ steps.manifest.outputs.version }}
        body: Minor Update - Updated google button
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Zip Extension
      run: zip -r My-Chrome-Tool-Set.zip . 

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: My-Chrome-Tool-Set
        path: ./My-Chrome-Tool-Set.zip
